version: '3.7'

networks:
  lan:
    driver: ${NETWORKS_DRIVER}

services:
  nginx:
    image: ${COMPOSE_PROJECT_NAME}-infra-nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx-container
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      lan:
        aliases:
          - ${APP_HOST}

  php-fpm: &php-base
    image: ${COMPOSE_PROJECT_NAME}-infra-php-fpm
    container_name: ${COMPOSE_PROJECT_NAME}-php-container
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TARGET_PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
    environment:
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - APP_NAME=${LARAVEL_APP_NAME}
      - APP_ENV=${LARAVEL_APP_ENV}
      - APP_KEY=${LARAVEL_APP_KEY}
      - APP_DEBUG=${LARAVEL_APP_DEBUG}
      - APP_URL=${LARAVEL_APP_URL}
      - LOG_CHANNEL=${LARAVEL_LOG_CHANNEL}
      - BROADCAST_DRIVER=${LARAVEL_BROADCAST_DRIVER}
      - CACHE_DRIVER=${LARAVEL_CACHE_DRIVER}
      - QUEUE_CONNECTION=${LARAVEL_QUEUE_CONNECTION}
      - SESSION_DRIVER=${LARAVEL_SESSION_DRIVER}
      - SESSION_LIFETIME=${LARAVEL_SESSION_LIFETIME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MAIL_DRIVER=${LARAVEL_MAIL_DRIVER}
      - MAIL_HOST=${LARAVEL_MAIL_HOST}
      - MAIL_PORT=${LARAVEL_MAIL_PORT}
      - MAIL_USERNAME=${LARAVEL_MAIL_USERNAME}
      - MAIL_PASSWORD=${LARAVEL_MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${LARAVEL_MAIL_ENCRYPTION}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    networks:
      - lan

  queues:
    <<: *php-base
    container_name: ${COMPOSE_PROJECT_NAME}-queues
    restart: unless-stopped
    command: bash -c "php artisan queue:work"
    
  mysql:
    image: ${COMPOSE_PROJECT_NAME}-infra-mysql
    container_name: ${COMPOSE_PROJECT_NAME}-mysql-container
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_VERSION=${MYSQL_VERSION}
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TZ=${TIMEZONE}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - lan

  redis:
      image: redis:alpine
      container_name: ${COMPOSE_PROJECT_NAME}-redis-container
      volumes:
      - ${DATA_PATH_HOST}:/data/redis
      ports:
      - "${REDIS_PORT}:6379"
      networks:
      - lan

  workspace:
    image: nqda/limalog
    build:
      context: .
      dockerfile: ./.docker/workspace/Dockerfile
      args:
        - DB_HOST=${MYSQL_HOST}
        - DB_PORT=${MYSQL_PORT}
        - DB_DATABASE=${MYSQL_DATABASE}
        - DB_USERNAME=${MYSQL_USER}
        - DB_PASSWORD=${MYSQL_PASSWORD}
        - APP_NAME=${LARAVEL_APP_NAME}
        - APP_ENV=${LARAVEL_APP_ENV}
        - APP_KEY=${LARAVEL_APP_KEY}
        - APP_DEBUG=${LARAVEL_APP_DEBUG}
        - APP_URL=${LARAVEL_APP_URL}
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TARGET_PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - "${WORKSPACE_HOST_SSH_PORT}:22"
